//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DangKiNgayLaoDong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiemDanhNgayLaoDong
    {
        public int id { get; set; }
        public Nullable<int> MSSV { get; set; }
        public Nullable<int> NguoiTao { get; set; }
        public string AnhTaoQR { get; set; }
    
        public virtual QuanLy QuanLy { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
