//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DangKiNgayLaoDong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuanLy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuanLy()
        {
            this.DiemDanhNgayLaoDongs = new HashSet<DiemDanhNgayLaoDong>();
            this.PhieuDuyets = new HashSet<PhieuDuyet>();
            this.PhieuXacNhanHoanThanhs = new HashSet<PhieuXacNhanHoanThanh>();
            this.TaoDotNgayLaoDongs = new HashSet<TaoDotNgayLaoDong>();
        }
    
        public int quanly_id { get; set; }
        public string hoten { get; set; }
        public string email { get; set; }
        public Nullable<bool> gioitinh { get; set; }
        public string diachi { get; set; }
        public string SDT { get; set; }
        public Nullable<int> taikhoan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiemDanhNgayLaoDong> DiemDanhNgayLaoDongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuDuyet> PhieuDuyets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuXacNhanHoanThanh> PhieuXacNhanHoanThanhs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaoDotNgayLaoDong> TaoDotNgayLaoDongs { get; set; }
        public virtual TaiKhoan TaiKhoan1 { get; set; }
    }
}
