//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DangKiNgayLaoDong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SinhVien()
        {
            this.DiemDanhNgayLaoDongs = new HashSet<DiemDanhNgayLaoDong>();
            this.PhieuDangKies = new HashSet<PhieuDangKy>();
            this.PhieuXacNhanHoanThanhs = new HashSet<PhieuXacNhanHoanThanh>();
            this.SoNgayLaoDongs = new HashSet<SoNgayLaoDong>();
        }
    
        public int MSSV { get; set; }
        public string hoten { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public string quequan { get; set; }
        public Nullable<bool> gioitinh { get; set; }
        public Nullable<int> taikhoan { get; set; }
        public string SDT { get; set; }
        public Nullable<int> lop_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiemDanhNgayLaoDong> DiemDanhNgayLaoDongs { get; set; }
        public virtual Lop Lop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuDangKy> PhieuDangKies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuXacNhanHoanThanh> PhieuXacNhanHoanThanhs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoNgayLaoDong> SoNgayLaoDongs { get; set; }
        public virtual TaiKhoan TaiKhoan1 { get; set; }
    }
}
