//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DangKiNgayLaoDong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaoDotNgayLaoDong
    {
        public int ID { get; set; }
        public string TenDotLaoDong { get; set; }
        public string MoTa { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> NguoiTao { get; set; }
    
        public virtual QuanLy QuanLy { get; set; }
    }
}
